//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssReader.RssReaderServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RssReaderServiceReference.IRssReader")]
    public interface IRssReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssReader/LoadFeedFromUrl", ReplyAction="http://tempuri.org/IRssReader/LoadFeedFromUrlResponse")]
        System.ServiceModel.Syndication.Rss20FeedFormatter LoadFeedFromUrl(string feedUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssReader/LoadFeedFromUrl", ReplyAction="http://tempuri.org/IRssReader/LoadFeedFromUrlResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Syndication.Rss20FeedFormatter> LoadFeedFromUrlAsync(string feedUrl);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRssReaderChannel : RssReader.RssReaderServiceReference.IRssReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RssReaderClient : System.ServiceModel.ClientBase<RssReader.RssReaderServiceReference.IRssReader>, RssReader.RssReaderServiceReference.IRssReader {
        
        public RssReaderClient() {
        }
        
        public RssReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RssReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RssReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RssReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ServiceModel.Syndication.Rss20FeedFormatter LoadFeedFromUrl(string feedUrl) {
            return base.Channel.LoadFeedFromUrl(feedUrl);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Syndication.Rss20FeedFormatter> LoadFeedFromUrlAsync(string feedUrl) {
            return base.Channel.LoadFeedFromUrlAsync(feedUrl);
        }
    }
}
